---
- name: when condition
  hosts: all
  tasks:
    - name: when condition
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Display the ouput of above module
      debug:
        var: a
    - name: create file f1 when f1 is not present
      file:
        name: /home/ubuntu/f1
        mode: 740
      when: a.stat.executable == false  

...
