---
- name: Error handling git edit
  hosts: all
  tasks:
    - block:
       - name: Install tomcat8
         apt:
          name: tomcat8
          state: present
          update_cache: yes
      rescue:
       - name: Install tomcat10
         apt:
          name: tomcat10
          state: present
          update_cache: yes
      always:
        - name: Dispaly msg
          debug:
            msg: Tomact was suceesfully installed


...
