---
- name: Configuring Apache2
  hosts: all
  tasks:
    - name: Downloading Apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: check url_response
    - name: Edit the index.html
      copy:
        content: "Hi apache how are you"
        dest: /var/www/html/index.html
      notify: restart apache2
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
    - name: check url_response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
          - http://172.31.91.192
          - http://172.31.81.97
...
